"""initial_schema

Revision ID: e947d07d071e
Revises: 
Create Date: 2026-07-03 13:45:27.946669
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e947d07d071e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketsnapshot',
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='ux_marketsnapshot_symbol_ts')
    )
    op.create_index(op.f('ix_marketsnapshot_symbol'), 'marketsnapshot', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('portfolio',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_table('holdings',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', postgresql.ENUM('STOCK', 'ETF', 'MUTUAL_FUND', 'CRYPTO', 'BOND', name='asset_type'), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_buy_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='ux_holdings_portfolio_symbol')
    )
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.create_table('portfoliosnapshot',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('invested_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfoliosnapshot_portfolio_created', 'portfoliosnapshot', ['portfolio_id', 'created_at'], unique=False)
    op.create_table('transactions',
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('BUY', 'SELL', 'DIVIDEND', 'BONUS', 'SPLIT', name='transaction_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_holding_id', 'transactions', ['holding_id'], unique=False)
    op.create_index('ix_transactions_timestamp', 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_holding_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_portfoliosnapshot_portfolio_created', table_name='portfoliosnapshot')
    op.drop_table('portfoliosnapshot')
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_marketsnapshot_symbol'), table_name='marketsnapshot')
    op.drop_table('marketsnapshot')
    # ### end Alembic commands ###
